### ISSUE TITLE
Lecteur musique

### ISSUE THREAD

**Issue by CharlesMassuard** [DorianLudm/SAE_PHP#8]
Réaliser le lecteur de musiques. 
On doit pouvoir play/pause/restart/next/previous/repeat
Le nom de la musique doit etre affiché
si possible affiché le nom du groupe/artiste et pochette de l'album ou musique

Doit passer automatiquement à la next musique quand musique finie

**Comment by DorianLudm** [comment]
Vraiment gros bravo pour cette fonctionnalité, tu t'es dépassé (et tu as casser tout le projet) mais franchement, ca vallais le coup :+1:
